version: '3.8'
services:
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-wahyujatirestu}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-task_manager}
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER:-wahyujatirestu} -d ${POSTGRES_DB:-task_manager}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        restart: unless-stopped
        env_file:
            - .env.docker
        depends_on:
            - db
        ports:
            - '8800:8800'
        volumes:
            - ./:/usr/src/app:delegated
        command: ['sh', './entrypoint.sh', 'npm', 'run', 'dev']
        # untuk production, ganti command menjadi ["sh","./entrypoint.sh","npm","start"]

volumes:
    db_data:
